# Generated by Django 2.2.4 on 2020-04-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(default='Unnamed dish', max_length=32)),
                ('dish_info', models.CharField(default='No info available', max_length=256)),
                ('dish_store', models.CharField(choices=[('Bayfront', 'Bayfront'), ('Bugis', 'Bugis'), ('Cecil', 'Cecil'), ('City Hall', 'City Hall'), ('Clifford Pier', 'Clifford Pier'), ('Marina Centre', 'Marina Centre'), ('Maxwell', 'Maxwell'), ('Tanjong Pagar', 'Tanjong Pagar')], default='Bugis', max_length=20)),
                ('dish_price', models.IntegerField(default=0.0)),
                ('photo', models.ImageField(default='static/images/no-default_image.jpg', null=True, upload_to='static/images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
