# Generated by Django 2.2.4 on 2020-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200410_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_info',
            field=models.TextField(default='No info available', max_length=256),
        ),
    ]
