# Generated by Django 2.2.4 on 2020-04-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200410_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.FloatField(default=0.0),
        ),
    ]
