# Generated by Django 2.2.4 on 2020-04-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200410_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.IntegerField(default=0),
        ),
    ]
