# Generated by Django 2.2.4 on 2020-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200413_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
