# Generated by Django 2.2.4 on 2020-04-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20200414_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
