# Generated by Django 2.2.4 on 2020-04-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_dish_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='photo',
            new_name='dish_image',
        ),
    ]
