# Generated by Django 2.2.4 on 2020-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20200414_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(default='default_image.jpg', null=True, upload_to='static/images'),
        ),
    ]
