# Generated by Django 2.2.4 on 2020-04-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20200414_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(default='Unnamed dish', max_length=64),
        ),
    ]
